{% set name = "df2gspread" %}
{% set version = "1.0.3" %}
{% set sha256 = "361e44f1b1f21fe9ab3b65eced78f99766b8a1c0d2f27c6214f8ae068b85159c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - google-api-python-client
    - gspread
    - oauth2client
    - pandas
    - pycrypto

test:
  imports:
    - df2gspread

about:
  home: https://github.com/maybelinot/df2gspread
  license: GPLv3
  summary: 'Manage Google Spreadsheets in Pandas DataFrame with Python'
  license_family: GPL
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  doc_url: http://df2gspread.readthedocs.io
  dev_url: https://github.com/maybelinot/df2gspread

extra:
  recipe-maintainers:
    - hadim
